# Generated by Django 5.0.7 on 2024-08-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usercustom_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='image',
            new_name='avatar',
        ),
    ]
