# Generated by Django 5.0.7 on 2024-08-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_use_balance',
        ),
    ]
