# Generated by Django 5.0.7 on 2024-08-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_alter_goal_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_amount',
        ),
    ]
